create table app_users (
    id bigint generated by default as identity,
    username varchar(64) not null,
    constraint pk_app_users primary key (id),
    constraint uk_app_users_username unique (username)
);

create table wallet_balances (
    id bigint generated by default as identity,
    user_id bigint not null,
    currency varchar(10) not null,
    balance numeric(38, 18) not null,
    constraint pk_wallet_balances primary key (id),
    constraint fk_wallet_balances_user foreign key (user_id) references app_users (id),
    constraint uk_wallet_balances_user_currency unique (user_id, currency),
    constraint ck_wallet_balances_currency check (currency in ('USDT', 'BTC', 'ETH'))
);

create table aggregated_prices (
    id bigint generated by default as identity,
    pair varchar(20) not null,
    bid_price numeric(38, 18) not null,
    bid_source varchar(64) not null,
    ask_price numeric(38, 18) not null,
    ask_source varchar(64) not null,
    fetched_at timestamp with time zone not null,
    constraint pk_aggregated_prices primary key (id),
    constraint ck_aggregated_prices_pair check (pair in ('BTCUSDT', 'ETHUSDT'))
);

create table trade_transactions (
    id bigint generated by default as identity,
    user_id bigint not null,
    pair varchar(20) not null,
    side varchar(10) not null,
    quantity numeric(38, 18) not null,
    price numeric(38, 18) not null,
    quote_amount numeric(38, 18) not null,
    base_currency varchar(10) not null,
    quote_currency varchar(10) not null,
    created_at timestamp with time zone not null,
    constraint pk_trade_transactions primary key (id),
    constraint fk_trade_transactions_user foreign key (user_id) references app_users (id),
    constraint ck_trade_transactions_pair check (pair in ('BTCUSDT', 'ETHUSDT')),
    constraint ck_trade_transactions_side check (side in ('BUY', 'SELL')),
    constraint ck_trade_transactions_base_currency check (base_currency in ('BTC', 'ETH')),
    constraint ck_trade_transactions_quote_currency check (quote_currency = 'USDT')
);
